/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApmsDothtmlRouteImport } from './routes/apms[.]html'
import { Route as ApiChangesRouteImport } from './routes/api/changes'
import { Route as ApiCompanyRouteImport } from './routes/api/company'
import { Route as ApiCompanyBackupsRouteImport } from './routes/api/company-backups'
import { Route as ApiCompanyLiveRouteImport } from './routes/api/company-live'
import { Route as ApiCompanyRestoreRouteImport } from './routes/api/company-restore'
import { Route as ApiCompanyTickRouteImport } from './routes/api/company-tick'
import { Route as ApiIssuedLoginsRouteImport } from './routes/api/issued-logins'
import { Route as ApiOrgRouteImport } from './routes/api/org'
import { Route as ApiPasswordResetRouteImport } from './routes/api/password-reset'
import { Route as ApiPeopleRouteImport } from './routes/api/people'
import { Route as ApiProvisionLoginsRouteImport } from './routes/api/provision-logins'
import { Route as ApiEKindRouteImport } from './routes/api/e.$kind'
import { Route as ApiMonthRecordsPeriodRouteImport } from './routes/api/month-records.$period'
import { Route as ApiOrgKindRouteImport } from './routes/api/org.$kind'
import { Route as ApiPeopleIdRouteImport } from './routes/api/people.$id'
import { Route as ApiRewardRecordsPeriodRouteImport } from './routes/api/reward-records.$period'
import { Route as ApiRosterPeriodRouteImport } from './routes/api/roster.$period'
import { Route as ApiTargetCellsIdRouteImport } from './routes/api/target-cells.$id'
import { Route as ApiEKindK1RouteImport } from './routes/api/e.$kind.$k1'
import { Route as ApiMonthRecordsPeriodPersonIdRouteImport } from './routes/api/month-records.$period.$personId'
import { Route as ApiOrgKindIdRouteImport } from './routes/api/org.$kind.$id'
import { Route as ApiRewardRecordsPeriodPersonIdRouteImport } from './routes/api/reward-records.$period.$personId'
import { Route as ApiRosterBindKindSubjectIdRouteImport } from './routes/api/roster-bind.$kind.$subjectId'
import { Route as ApiRosterPeriodLockRouteImport } from './routes/api/roster.$period.lock'
import { Route as ApiRosterPeriodUnlockRouteImport } from './routes/api/roster.$period.unlock'
import { Route as ApiEKindK1K2RouteImport } from './routes/api/e.$kind.$k1.$k2'
import { Route as ApiRosterBindKindSubjectIdRebindRouteImport } from './routes/api/roster-bind.$kind.$subjectId.rebind'
import { Route as ApiRosterPeriodCopyFromFromPeriodRouteImport } from './routes/api/roster.$period.copy-from.$fromPeriod'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApmsDothtmlRoute = ApmsDothtmlRouteImport.update({
  id: '/apms.html',
  path: '/apms.html',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChangesRoute = ApiChangesRouteImport.update({
  id: '/api/changes',
  path: '/api/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanyRoute = ApiCompanyRouteImport.update({
  id: '/api/company',
  path: '/api/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanyBackupsRoute = ApiCompanyBackupsRouteImport.update({
  id: '/api/company-backups',
  path: '/api/company-backups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanyLiveRoute = ApiCompanyLiveRouteImport.update({
  id: '/api/company-live',
  path: '/api/company-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanyRestoreRoute = ApiCompanyRestoreRouteImport.update({
  id: '/api/company-restore',
  path: '/api/company-restore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanyTickRoute = ApiCompanyTickRouteImport.update({
  id: '/api/company-tick',
  path: '/api/company-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIssuedLoginsRoute = ApiIssuedLoginsRouteImport.update({
  id: '/api/issued-logins',
  path: '/api/issued-logins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgRoute = ApiOrgRouteImport.update({
  id: '/api/org',
  path: '/api/org',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordResetRoute = ApiPasswordResetRouteImport.update({
  id: '/api/password-reset',
  path: '/api/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeopleRoute = ApiPeopleRouteImport.update({
  id: '/api/people',
  path: '/api/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvisionLoginsRoute = ApiProvisionLoginsRouteImport.update({
  id: '/api/provision-logins',
  path: '/api/provision-logins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEKindRoute = ApiEKindRouteImport.update({
  id: '/api/e/$kind',
  path: '/api/e/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonthRecordsPeriodRoute = ApiMonthRecordsPeriodRouteImport.update({
  id: '/api/month-records/$period',
  path: '/api/month-records/$period',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgKindRoute = ApiOrgKindRouteImport.update({
  id: '/$kind',
  path: '/$kind',
  getParentRoute: () => ApiOrgRoute,
} as any)
const ApiPeopleIdRoute = ApiPeopleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPeopleRoute,
} as any)
const ApiRewardRecordsPeriodRoute = ApiRewardRecordsPeriodRouteImport.update({
  id: '/api/reward-records/$period',
  path: '/api/reward-records/$period',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRosterPeriodRoute = ApiRosterPeriodRouteImport.update({
  id: '/api/roster/$period',
  path: '/api/roster/$period',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTargetCellsIdRoute = ApiTargetCellsIdRouteImport.update({
  id: '/api/target-cells/$id',
  path: '/api/target-cells/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEKindK1Route = ApiEKindK1RouteImport.update({
  id: '/$k1',
  path: '/$k1',
  getParentRoute: () => ApiEKindRoute,
} as any)
const ApiMonthRecordsPeriodPersonIdRoute =
  ApiMonthRecordsPeriodPersonIdRouteImport.update({
    id: '/$personId',
    path: '/$personId',
    getParentRoute: () => ApiMonthRecordsPeriodRoute,
  } as any)
const ApiOrgKindIdRoute = ApiOrgKindIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiOrgKindRoute,
} as any)
const ApiRewardRecordsPeriodPersonIdRoute =
  ApiRewardRecordsPeriodPersonIdRouteImport.update({
    id: '/$personId',
    path: '/$personId',
    getParentRoute: () => ApiRewardRecordsPeriodRoute,
  } as any)
const ApiRosterBindKindSubjectIdRoute =
  ApiRosterBindKindSubjectIdRouteImport.update({
    id: '/api/roster-bind/$kind/$subjectId',
    path: '/api/roster-bind/$kind/$subjectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRosterPeriodLockRoute = ApiRosterPeriodLockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => ApiRosterPeriodRoute,
} as any)
const ApiRosterPeriodUnlockRoute = ApiRosterPeriodUnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => ApiRosterPeriodRoute,
} as any)
const ApiEKindK1K2Route = ApiEKindK1K2RouteImport.update({
  id: '/$k2',
  path: '/$k2',
  getParentRoute: () => ApiEKindK1Route,
} as any)
const ApiRosterBindKindSubjectIdRebindRoute =
  ApiRosterBindKindSubjectIdRebindRouteImport.update({
    id: '/rebind',
    path: '/rebind',
    getParentRoute: () => ApiRosterBindKindSubjectIdRoute,
  } as any)
const ApiRosterPeriodCopyFromFromPeriodRoute =
  ApiRosterPeriodCopyFromFromPeriodRouteImport.update({
    id: '/copy-from/$fromPeriod',
    path: '/copy-from/$fromPeriod',
    getParentRoute: () => ApiRosterPeriodRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apms.html': typeof ApmsDothtmlRoute
  '/api/changes': typeof ApiChangesRoute
  '/api/company': typeof ApiCompanyRoute
  '/api/company-backups': typeof ApiCompanyBackupsRoute
  '/api/company-live': typeof ApiCompanyLiveRoute
  '/api/company-restore': typeof ApiCompanyRestoreRoute
  '/api/company-tick': typeof ApiCompanyTickRoute
  '/api/issued-logins': typeof ApiIssuedLoginsRoute
  '/api/org': typeof ApiOrgRouteWithChildren
  '/api/password-reset': typeof ApiPasswordResetRoute
  '/api/people': typeof ApiPeopleRouteWithChildren
  '/api/provision-logins': typeof ApiProvisionLoginsRoute
  '/api/e/$kind': typeof ApiEKindRouteWithChildren
  '/api/month-records/$period': typeof ApiMonthRecordsPeriodRouteWithChildren
  '/api/org/$kind': typeof ApiOrgKindRouteWithChildren
  '/api/people/$id': typeof ApiPeopleIdRoute
  '/api/reward-records/$period': typeof ApiRewardRecordsPeriodRouteWithChildren
  '/api/roster/$period': typeof ApiRosterPeriodRouteWithChildren
  '/api/target-cells/$id': typeof ApiTargetCellsIdRoute
  '/api/e/$kind/$k1': typeof ApiEKindK1RouteWithChildren
  '/api/month-records/$period/$personId': typeof ApiMonthRecordsPeriodPersonIdRoute
  '/api/org/$kind/$id': typeof ApiOrgKindIdRoute
  '/api/reward-records/$period/$personId': typeof ApiRewardRecordsPeriodPersonIdRoute
  '/api/roster-bind/$kind/$subjectId': typeof ApiRosterBindKindSubjectIdRouteWithChildren
  '/api/roster/$period/lock': typeof ApiRosterPeriodLockRoute
  '/api/roster/$period/unlock': typeof ApiRosterPeriodUnlockRoute
  '/api/e/$kind/$k1/$k2': typeof ApiEKindK1K2Route
  '/api/roster-bind/$kind/$subjectId/rebind': typeof ApiRosterBindKindSubjectIdRebindRoute
  '/api/roster/$period/copy-from/$fromPeriod': typeof ApiRosterPeriodCopyFromFromPeriodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apms.html': typeof ApmsDothtmlRoute
  '/api/changes': typeof ApiChangesRoute
  '/api/company': typeof ApiCompanyRoute
  '/api/company-backups': typeof ApiCompanyBackupsRoute
  '/api/company-live': typeof ApiCompanyLiveRoute
  '/api/company-restore': typeof ApiCompanyRestoreRoute
  '/api/company-tick': typeof ApiCompanyTickRoute
  '/api/issued-logins': typeof ApiIssuedLoginsRoute
  '/api/org': typeof ApiOrgRouteWithChildren
  '/api/password-reset': typeof ApiPasswordResetRoute
  '/api/people': typeof ApiPeopleRouteWithChildren
  '/api/provision-logins': typeof ApiProvisionLoginsRoute
  '/api/e/$kind': typeof ApiEKindRouteWithChildren
  '/api/month-records/$period': typeof ApiMonthRecordsPeriodRouteWithChildren
  '/api/org/$kind': typeof ApiOrgKindRouteWithChildren
  '/api/people/$id': typeof ApiPeopleIdRoute
  '/api/reward-records/$period': typeof ApiRewardRecordsPeriodRouteWithChildren
  '/api/roster/$period': typeof ApiRosterPeriodRouteWithChildren
  '/api/target-cells/$id': typeof ApiTargetCellsIdRoute
  '/api/e/$kind/$k1': typeof ApiEKindK1RouteWithChildren
  '/api/month-records/$period/$personId': typeof ApiMonthRecordsPeriodPersonIdRoute
  '/api/org/$kind/$id': typeof ApiOrgKindIdRoute
  '/api/reward-records/$period/$personId': typeof ApiRewardRecordsPeriodPersonIdRoute
  '/api/roster-bind/$kind/$subjectId': typeof ApiRosterBindKindSubjectIdRouteWithChildren
  '/api/roster/$period/lock': typeof ApiRosterPeriodLockRoute
  '/api/roster/$period/unlock': typeof ApiRosterPeriodUnlockRoute
  '/api/e/$kind/$k1/$k2': typeof ApiEKindK1K2Route
  '/api/roster-bind/$kind/$subjectId/rebind': typeof ApiRosterBindKindSubjectIdRebindRoute
  '/api/roster/$period/copy-from/$fromPeriod': typeof ApiRosterPeriodCopyFromFromPeriodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apms.html': typeof ApmsDothtmlRoute
  '/api/changes': typeof ApiChangesRoute
  '/api/company': typeof ApiCompanyRoute
  '/api/company-backups': typeof ApiCompanyBackupsRoute
  '/api/company-live': typeof ApiCompanyLiveRoute
  '/api/company-restore': typeof ApiCompanyRestoreRoute
  '/api/company-tick': typeof ApiCompanyTickRoute
  '/api/issued-logins': typeof ApiIssuedLoginsRoute
  '/api/org': typeof ApiOrgRouteWithChildren
  '/api/password-reset': typeof ApiPasswordResetRoute
  '/api/people': typeof ApiPeopleRouteWithChildren
  '/api/provision-logins': typeof ApiProvisionLoginsRoute
  '/api/e/$kind': typeof ApiEKindRouteWithChildren
  '/api/month-records/$period': typeof ApiMonthRecordsPeriodRouteWithChildren
  '/api/org/$kind': typeof ApiOrgKindRouteWithChildren
  '/api/people/$id': typeof ApiPeopleIdRoute
  '/api/reward-records/$period': typeof ApiRewardRecordsPeriodRouteWithChildren
  '/api/roster/$period': typeof ApiRosterPeriodRouteWithChildren
  '/api/target-cells/$id': typeof ApiTargetCellsIdRoute
  '/api/e/$kind/$k1': typeof ApiEKindK1RouteWithChildren
  '/api/month-records/$period/$personId': typeof ApiMonthRecordsPeriodPersonIdRoute
  '/api/org/$kind/$id': typeof ApiOrgKindIdRoute
  '/api/reward-records/$period/$personId': typeof ApiRewardRecordsPeriodPersonIdRoute
  '/api/roster-bind/$kind/$subjectId': typeof ApiRosterBindKindSubjectIdRouteWithChildren
  '/api/roster/$period/lock': typeof ApiRosterPeriodLockRoute
  '/api/roster/$period/unlock': typeof ApiRosterPeriodUnlockRoute
  '/api/e/$kind/$k1/$k2': typeof ApiEKindK1K2Route
  '/api/roster-bind/$kind/$subjectId/rebind': typeof ApiRosterBindKindSubjectIdRebindRoute
  '/api/roster/$period/copy-from/$fromPeriod': typeof ApiRosterPeriodCopyFromFromPeriodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apms.html'
    | '/api/changes'
    | '/api/company'
    | '/api/company-backups'
    | '/api/company-live'
    | '/api/company-restore'
    | '/api/company-tick'
    | '/api/issued-logins'
    | '/api/org'
    | '/api/password-reset'
    | '/api/people'
    | '/api/provision-logins'
    | '/api/e/$kind'
    | '/api/month-records/$period'
    | '/api/org/$kind'
    | '/api/people/$id'
    | '/api/reward-records/$period'
    | '/api/roster/$period'
    | '/api/target-cells/$id'
    | '/api/e/$kind/$k1'
    | '/api/month-records/$period/$personId'
    | '/api/org/$kind/$id'
    | '/api/reward-records/$period/$personId'
    | '/api/roster-bind/$kind/$subjectId'
    | '/api/roster/$period/lock'
    | '/api/roster/$period/unlock'
    | '/api/e/$kind/$k1/$k2'
    | '/api/roster-bind/$kind/$subjectId/rebind'
    | '/api/roster/$period/copy-from/$fromPeriod'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apms.html'
    | '/api/changes'
    | '/api/company'
    | '/api/company-backups'
    | '/api/company-live'
    | '/api/company-restore'
    | '/api/company-tick'
    | '/api/issued-logins'
    | '/api/org'
    | '/api/password-reset'
    | '/api/people'
    | '/api/provision-logins'
    | '/api/e/$kind'
    | '/api/month-records/$period'
    | '/api/org/$kind'
    | '/api/people/$id'
    | '/api/reward-records/$period'
    | '/api/roster/$period'
    | '/api/target-cells/$id'
    | '/api/e/$kind/$k1'
    | '/api/month-records/$period/$personId'
    | '/api/org/$kind/$id'
    | '/api/reward-records/$period/$personId'
    | '/api/roster-bind/$kind/$subjectId'
    | '/api/roster/$period/lock'
    | '/api/roster/$period/unlock'
    | '/api/e/$kind/$k1/$k2'
    | '/api/roster-bind/$kind/$subjectId/rebind'
    | '/api/roster/$period/copy-from/$fromPeriod'
  id:
    | '__root__'
    | '/'
    | '/apms.html'
    | '/api/changes'
    | '/api/company'
    | '/api/company-backups'
    | '/api/company-live'
    | '/api/company-restore'
    | '/api/company-tick'
    | '/api/issued-logins'
    | '/api/org'
    | '/api/password-reset'
    | '/api/people'
    | '/api/provision-logins'
    | '/api/e/$kind'
    | '/api/month-records/$period'
    | '/api/org/$kind'
    | '/api/people/$id'
    | '/api/reward-records/$period'
    | '/api/roster/$period'
    | '/api/target-cells/$id'
    | '/api/e/$kind/$k1'
    | '/api/month-records/$period/$personId'
    | '/api/org/$kind/$id'
    | '/api/reward-records/$period/$personId'
    | '/api/roster-bind/$kind/$subjectId'
    | '/api/roster/$period/lock'
    | '/api/roster/$period/unlock'
    | '/api/e/$kind/$k1/$k2'
    | '/api/roster-bind/$kind/$subjectId/rebind'
    | '/api/roster/$period/copy-from/$fromPeriod'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApmsDothtmlRoute: typeof ApmsDothtmlRoute
  ApiChangesRoute: typeof ApiChangesRoute
  ApiCompanyRoute: typeof ApiCompanyRoute
  ApiCompanyBackupsRoute: typeof ApiCompanyBackupsRoute
  ApiCompanyLiveRoute: typeof ApiCompanyLiveRoute
  ApiCompanyRestoreRoute: typeof ApiCompanyRestoreRoute
  ApiCompanyTickRoute: typeof ApiCompanyTickRoute
  ApiIssuedLoginsRoute: typeof ApiIssuedLoginsRoute
  ApiOrgRoute: typeof ApiOrgRouteWithChildren
  ApiPasswordResetRoute: typeof ApiPasswordResetRoute
  ApiPeopleRoute: typeof ApiPeopleRouteWithChildren
  ApiProvisionLoginsRoute: typeof ApiProvisionLoginsRoute
  ApiEKindRoute: typeof ApiEKindRouteWithChildren
  ApiMonthRecordsPeriodRoute: typeof ApiMonthRecordsPeriodRouteWithChildren
  ApiRewardRecordsPeriodRoute: typeof ApiRewardRecordsPeriodRouteWithChildren
  ApiRosterPeriodRoute: typeof ApiRosterPeriodRouteWithChildren
  ApiTargetCellsIdRoute: typeof ApiTargetCellsIdRoute
  ApiRosterBindKindSubjectIdRoute: typeof ApiRosterBindKindSubjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apms.html': {
      id: '/apms.html'
      path: '/apms.html'
      fullPath: '/apms.html'
      preLoaderRoute: typeof ApmsDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/changes': {
      id: '/api/changes'
      path: '/api/changes'
      fullPath: '/api/changes'
      preLoaderRoute: typeof ApiChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/company': {
      id: '/api/company'
      path: '/api/company'
      fullPath: '/api/company'
      preLoaderRoute: typeof ApiCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/company-backups': {
      id: '/api/company-backups'
      path: '/api/company-backups'
      fullPath: '/api/company-backups'
      preLoaderRoute: typeof ApiCompanyBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/company-live': {
      id: '/api/company-live'
      path: '/api/company-live'
      fullPath: '/api/company-live'
      preLoaderRoute: typeof ApiCompanyLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/company-restore': {
      id: '/api/company-restore'
      path: '/api/company-restore'
      fullPath: '/api/company-restore'
      preLoaderRoute: typeof ApiCompanyRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/company-tick': {
      id: '/api/company-tick'
      path: '/api/company-tick'
      fullPath: '/api/company-tick'
      preLoaderRoute: typeof ApiCompanyTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/issued-logins': {
      id: '/api/issued-logins'
      path: '/api/issued-logins'
      fullPath: '/api/issued-logins'
      preLoaderRoute: typeof ApiIssuedLoginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org': {
      id: '/api/org'
      path: '/api/org'
      fullPath: '/api/org'
      preLoaderRoute: typeof ApiOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/password-reset': {
      id: '/api/password-reset'
      path: '/api/password-reset'
      fullPath: '/api/password-reset'
      preLoaderRoute: typeof ApiPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/people': {
      id: '/api/people'
      path: '/api/people'
      fullPath: '/api/people'
      preLoaderRoute: typeof ApiPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provision-logins': {
      id: '/api/provision-logins'
      path: '/api/provision-logins'
      fullPath: '/api/provision-logins'
      preLoaderRoute: typeof ApiProvisionLoginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e/$kind': {
      id: '/api/e/$kind'
      path: '/api/e/$kind'
      fullPath: '/api/e/$kind'
      preLoaderRoute: typeof ApiEKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/month-records/$period': {
      id: '/api/month-records/$period'
      path: '/api/month-records/$period'
      fullPath: '/api/month-records/$period'
      preLoaderRoute: typeof ApiMonthRecordsPeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/$kind': {
      id: '/api/org/$kind'
      path: '/$kind'
      fullPath: '/api/org/$kind'
      preLoaderRoute: typeof ApiOrgKindRouteImport
      parentRoute: typeof ApiOrgRoute
    }
    '/api/people/$id': {
      id: '/api/people/$id'
      path: '/$id'
      fullPath: '/api/people/$id'
      preLoaderRoute: typeof ApiPeopleIdRouteImport
      parentRoute: typeof ApiPeopleRoute
    }
    '/api/reward-records/$period': {
      id: '/api/reward-records/$period'
      path: '/api/reward-records/$period'
      fullPath: '/api/reward-records/$period'
      preLoaderRoute: typeof ApiRewardRecordsPeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roster/$period': {
      id: '/api/roster/$period'
      path: '/api/roster/$period'
      fullPath: '/api/roster/$period'
      preLoaderRoute: typeof ApiRosterPeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/target-cells/$id': {
      id: '/api/target-cells/$id'
      path: '/api/target-cells/$id'
      fullPath: '/api/target-cells/$id'
      preLoaderRoute: typeof ApiTargetCellsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e/$kind/$k1': {
      id: '/api/e/$kind/$k1'
      path: '/$k1'
      fullPath: '/api/e/$kind/$k1'
      preLoaderRoute: typeof ApiEKindK1RouteImport
      parentRoute: typeof ApiEKindRoute
    }
    '/api/month-records/$period/$personId': {
      id: '/api/month-records/$period/$personId'
      path: '/$personId'
      fullPath: '/api/month-records/$period/$personId'
      preLoaderRoute: typeof ApiMonthRecordsPeriodPersonIdRouteImport
      parentRoute: typeof ApiMonthRecordsPeriodRoute
    }
    '/api/org/$kind/$id': {
      id: '/api/org/$kind/$id'
      path: '/$id'
      fullPath: '/api/org/$kind/$id'
      preLoaderRoute: typeof ApiOrgKindIdRouteImport
      parentRoute: typeof ApiOrgKindRoute
    }
    '/api/reward-records/$period/$personId': {
      id: '/api/reward-records/$period/$personId'
      path: '/$personId'
      fullPath: '/api/reward-records/$period/$personId'
      preLoaderRoute: typeof ApiRewardRecordsPeriodPersonIdRouteImport
      parentRoute: typeof ApiRewardRecordsPeriodRoute
    }
    '/api/roster-bind/$kind/$subjectId': {
      id: '/api/roster-bind/$kind/$subjectId'
      path: '/api/roster-bind/$kind/$subjectId'
      fullPath: '/api/roster-bind/$kind/$subjectId'
      preLoaderRoute: typeof ApiRosterBindKindSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roster/$period/lock': {
      id: '/api/roster/$period/lock'
      path: '/lock'
      fullPath: '/api/roster/$period/lock'
      preLoaderRoute: typeof ApiRosterPeriodLockRouteImport
      parentRoute: typeof ApiRosterPeriodRoute
    }
    '/api/roster/$period/unlock': {
      id: '/api/roster/$period/unlock'
      path: '/unlock'
      fullPath: '/api/roster/$period/unlock'
      preLoaderRoute: typeof ApiRosterPeriodUnlockRouteImport
      parentRoute: typeof ApiRosterPeriodRoute
    }
    '/api/e/$kind/$k1/$k2': {
      id: '/api/e/$kind/$k1/$k2'
      path: '/$k2'
      fullPath: '/api/e/$kind/$k1/$k2'
      preLoaderRoute: typeof ApiEKindK1K2RouteImport
      parentRoute: typeof ApiEKindK1Route
    }
    '/api/roster-bind/$kind/$subjectId/rebind': {
      id: '/api/roster-bind/$kind/$subjectId/rebind'
      path: '/rebind'
      fullPath: '/api/roster-bind/$kind/$subjectId/rebind'
      preLoaderRoute: typeof ApiRosterBindKindSubjectIdRebindRouteImport
      parentRoute: typeof ApiRosterBindKindSubjectIdRoute
    }
    '/api/roster/$period/copy-from/$fromPeriod': {
      id: '/api/roster/$period/copy-from/$fromPeriod'
      path: '/copy-from/$fromPeriod'
      fullPath: '/api/roster/$period/copy-from/$fromPeriod'
      preLoaderRoute: typeof ApiRosterPeriodCopyFromFromPeriodRouteImport
      parentRoute: typeof ApiRosterPeriodRoute
    }
  }
}

interface ApiOrgKindRouteChildren {
  ApiOrgKindIdRoute: typeof ApiOrgKindIdRoute
}

const ApiOrgKindRouteChildren: ApiOrgKindRouteChildren = {
  ApiOrgKindIdRoute: ApiOrgKindIdRoute,
}

const ApiOrgKindRouteWithChildren = ApiOrgKindRoute._addFileChildren(
  ApiOrgKindRouteChildren,
)

interface ApiOrgRouteChildren {
  ApiOrgKindRoute: typeof ApiOrgKindRouteWithChildren
}

const ApiOrgRouteChildren: ApiOrgRouteChildren = {
  ApiOrgKindRoute: ApiOrgKindRouteWithChildren,
}

const ApiOrgRouteWithChildren =
  ApiOrgRoute._addFileChildren(ApiOrgRouteChildren)

interface ApiPeopleRouteChildren {
  ApiPeopleIdRoute: typeof ApiPeopleIdRoute
}

const ApiPeopleRouteChildren: ApiPeopleRouteChildren = {
  ApiPeopleIdRoute: ApiPeopleIdRoute,
}

const ApiPeopleRouteWithChildren = ApiPeopleRoute._addFileChildren(
  ApiPeopleRouteChildren,
)

interface ApiEKindK1RouteChildren {
  ApiEKindK1K2Route: typeof ApiEKindK1K2Route
}

const ApiEKindK1RouteChildren: ApiEKindK1RouteChildren = {
  ApiEKindK1K2Route: ApiEKindK1K2Route,
}

const ApiEKindK1RouteWithChildren = ApiEKindK1Route._addFileChildren(
  ApiEKindK1RouteChildren,
)

interface ApiEKindRouteChildren {
  ApiEKindK1Route: typeof ApiEKindK1RouteWithChildren
}

const ApiEKindRouteChildren: ApiEKindRouteChildren = {
  ApiEKindK1Route: ApiEKindK1RouteWithChildren,
}

const ApiEKindRouteWithChildren = ApiEKindRoute._addFileChildren(
  ApiEKindRouteChildren,
)

interface ApiMonthRecordsPeriodRouteChildren {
  ApiMonthRecordsPeriodPersonIdRoute: typeof ApiMonthRecordsPeriodPersonIdRoute
}

const ApiMonthRecordsPeriodRouteChildren: ApiMonthRecordsPeriodRouteChildren = {
  ApiMonthRecordsPeriodPersonIdRoute: ApiMonthRecordsPeriodPersonIdRoute,
}

const ApiMonthRecordsPeriodRouteWithChildren =
  ApiMonthRecordsPeriodRoute._addFileChildren(
    ApiMonthRecordsPeriodRouteChildren,
  )

interface ApiRewardRecordsPeriodRouteChildren {
  ApiRewardRecordsPeriodPersonIdRoute: typeof ApiRewardRecordsPeriodPersonIdRoute
}

const ApiRewardRecordsPeriodRouteChildren: ApiRewardRecordsPeriodRouteChildren =
  {
    ApiRewardRecordsPeriodPersonIdRoute: ApiRewardRecordsPeriodPersonIdRoute,
  }

const ApiRewardRecordsPeriodRouteWithChildren =
  ApiRewardRecordsPeriodRoute._addFileChildren(
    ApiRewardRecordsPeriodRouteChildren,
  )

interface ApiRosterPeriodRouteChildren {
  ApiRosterPeriodLockRoute: typeof ApiRosterPeriodLockRoute
  ApiRosterPeriodUnlockRoute: typeof ApiRosterPeriodUnlockRoute
  ApiRosterPeriodCopyFromFromPeriodRoute: typeof ApiRosterPeriodCopyFromFromPeriodRoute
}

const ApiRosterPeriodRouteChildren: ApiRosterPeriodRouteChildren = {
  ApiRosterPeriodLockRoute: ApiRosterPeriodLockRoute,
  ApiRosterPeriodUnlockRoute: ApiRosterPeriodUnlockRoute,
  ApiRosterPeriodCopyFromFromPeriodRoute:
    ApiRosterPeriodCopyFromFromPeriodRoute,
}

const ApiRosterPeriodRouteWithChildren = ApiRosterPeriodRoute._addFileChildren(
  ApiRosterPeriodRouteChildren,
)

interface ApiRosterBindKindSubjectIdRouteChildren {
  ApiRosterBindKindSubjectIdRebindRoute: typeof ApiRosterBindKindSubjectIdRebindRoute
}

const ApiRosterBindKindSubjectIdRouteChildren: ApiRosterBindKindSubjectIdRouteChildren =
  {
    ApiRosterBindKindSubjectIdRebindRoute:
      ApiRosterBindKindSubjectIdRebindRoute,
  }

const ApiRosterBindKindSubjectIdRouteWithChildren =
  ApiRosterBindKindSubjectIdRoute._addFileChildren(
    ApiRosterBindKindSubjectIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApmsDothtmlRoute: ApmsDothtmlRoute,
  ApiChangesRoute: ApiChangesRoute,
  ApiCompanyRoute: ApiCompanyRoute,
  ApiCompanyBackupsRoute: ApiCompanyBackupsRoute,
  ApiCompanyLiveRoute: ApiCompanyLiveRoute,
  ApiCompanyRestoreRoute: ApiCompanyRestoreRoute,
  ApiCompanyTickRoute: ApiCompanyTickRoute,
  ApiIssuedLoginsRoute: ApiIssuedLoginsRoute,
  ApiOrgRoute: ApiOrgRouteWithChildren,
  ApiPasswordResetRoute: ApiPasswordResetRoute,
  ApiPeopleRoute: ApiPeopleRouteWithChildren,
  ApiProvisionLoginsRoute: ApiProvisionLoginsRoute,
  ApiEKindRoute: ApiEKindRouteWithChildren,
  ApiMonthRecordsPeriodRoute: ApiMonthRecordsPeriodRouteWithChildren,
  ApiRewardRecordsPeriodRoute: ApiRewardRecordsPeriodRouteWithChildren,
  ApiRosterPeriodRoute: ApiRosterPeriodRouteWithChildren,
  ApiTargetCellsIdRoute: ApiTargetCellsIdRoute,
  ApiRosterBindKindSubjectIdRoute: ApiRosterBindKindSubjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
